image: docker:latest

services:
  - docker:dind

stages:
  - BuildImage
  - TestApi
  - TestUi

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

BuildImage:
  stage: BuildImage
  script:
    - docker build -t test-cars .
  artifacts:
    name: "test-cars-image"
    paths:
      - test-cars.tar
    expire_in: 8 hours

TestApi:
  stage: TestApi
  script:
    - docker build -t test-cars .
    - docker run --rm --name test-cars-api test-cars bash -c "./run_api_tests.sh"
  artifacts:
    paths:
      - tests/results/api_results.txt
    expire_in: 8 hours
  when: manual

TestUi:
  stage: TestUi
  script:
    - docker build -t test-cars .
    - docker run --rm --name test-cars-ui test-cars bash -c "./run_ui_tests.sh"
  artifacts:
    paths:
      - tests/results/ui_results.txt
    expire_in: 8 hours
  when: manual
  needs:
    - job: TestApi
