image: docker:latest

services:
  - docker:dind

stages:
  - BuildImage
  - TestApi
  - TestUi

variables:
  DOCKER_DRIVER: overlay2


TestApi:
  stage: test_api
  script:
    - docker build -t test-cars . 
    - docker run --name test-cars-api test-cars bash -c "pytest -s -v tests/test_app.py > tests/results/api_results.txt"  # Запускаем API тесты и сохраняем в файл
  artifacts:
    paths:
      - tests/results/api_results.txt 
    expire_in: 8 hours 
  when: manual  


TestUi:
  stage: test_ui
  script:
    - docker build -t test-cars . 
    - docker run --name test-cars-ui test-cars bash -c "pytest -s -v tests/test_ui.py > tests/results/ui_results.txt"  # Запускаем UI тесты и сохраняем в файл
  artifacts:
    paths:
      - tests/results/ui_results.txt 
    expire_in: 8 hours  
  when: manual  
  needs:
    - job: test_api  
